SET FOREIGN_KEY_CHECKS = 0;
SET GROUP_CONCAT_MAX_LEN=32768;
SET @tables = NULL;
SELECT GROUP_CONCAT('`', table_name, '`') INTO @tables
  FROM information_schema.tables
  WHERE table_schema = (SELECT DATABASE());
SELECT IFNULL(@tables,'dummy') INTO @tables;

SET @tables = CONCAT('DROP TABLE IF EXISTS ', @tables);
PREPARE stmt FROM @tables;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET FOREIGN_KEY_CHECKS = 1;



DROP PROCEDURE IF EXISTS `smaw_unittest`.`SMAWSP_ADMIN_CREATE_SKIN`;
DROP PROCEDURE IF EXISTS `smaw_unittest`.`SMAWSP_ADMIN_DEL_MENU`;
DROP PROCEDURE IF EXISTS `smaw_unittest`.`SMAWSP_ADMIN_DEL_MERCHANT`;
DROP PROCEDURE IF EXISTS `smaw_unittest`.`SMAWSP_ADMIN_DEL_MERCHANT_PRICE_RECORDS`;
DROP PROCEDURE IF EXISTS `smaw_unittest`.`SMAWSP_ADMIN_IMGM_DELETER`;
DROP PROCEDURE IF EXISTS `smaw_unittest`.`SMAWSP_ADMIN_IMIM_DELETER`;
DROP PROCEDURE IF EXISTS `smaw_unittest`.`SMAWSP_CANCEL_ORDER_MESSAGES`;
DROP PROCEDURE IF EXISTS `smaw_unittest`.`SMAWSP_CLEAR_OLD_ERROR_LOG`;
DROP PROCEDURE IF EXISTS `smaw_unittest`.`SMAWSP_CREATE_COB_ACTIVITIES`;
DROP PROCEDURE IF EXISTS `smaw_unittest`.`SMAWSP_CREATE_COB_MESSAGES`;
DROP PROCEDURE IF EXISTS `smaw_unittest`.`SMAWSP_CREATE_DAILY_REPORT_FILE`;
DROP PROCEDURE IF EXISTS `smaw_unittest`.`SMAWSP_CREATE_MORNING_MESSAGES`;
DROP PROCEDURE IF EXISTS `smaw_unittest`.`SMAWSP_CREATE_ORDER`;
DROP PROCEDURE IF EXISTS `smaw_unittest`.`SMAWSP_CREATE_ORDER_MESSAGES`;
DROP PROCEDURE IF EXISTS `smaw_unittest`.`SMAWSP_HOLIDAY_HOUR`;
DROP PROCEDURE IF EXISTS `smaw_unittest`.`SMAWSP_INCREMENT_MENU_KEY`;
DROP PROCEDURE IF EXISTS `smaw_unittest`.`SMAWSP_MENU_CHANGE_SCHEDULER`;
DROP PROCEDURE IF EXISTS `smaw_unittest`.`SMAWSP_rpt_Weekly`;
DROP PROCEDURE IF EXISTS `smaw_unittest`.`smawsp_tester`;
DROP PROCEDURE IF EXISTS `smaw_unittest`.`SMAWSP_UPDATE_BALANCE`;
DROP PROCEDURE IF EXISTS `smaw_unittest`.`SMAWSP_USER_BALANCE_CHANGE`;
DROP PROCEDURE IF EXISTS `smaw_unittest`.`SMAWSP_USER_CREATION_DATA_CREATE`;
DROP FUNCTION IF EXISTS `smaw_unittest`.`strip_punc`;
DROP VIEW IF EXISTS `smaw_unittest`.`smawv_mmm_status`;